CANONICAL_NODE_MAP = {
    "EVALUATION_FRAMEWORKS": "EVALUATION",
    "EMBEDDINGS_RETRIEVAL": "EMBEDDINGS",
    "PRODUCT_ENGINEERING_BACKGROUND": "PRODUCT_ENGINEERING",
    "VECTOR_DATABASES": "VECTOR_DB"
}
